#! /bin/sh

# Startup applications

killall picom 
picom --config ~/.config/picom/picom.sample.conf &

#wal -i /home/paper/Imagens/wallpapers/edward-hopper/6eplMP.jpg -n                                                     # Pywall set wallpaper and color scheme
wal -R
#killall nitrogen
#nitrogen --restore                                       # Nitrogen set wallpaper

killall dunst
dunst -conf $HOME/.config/dunst/dunstrc-bspwm &

killall polybar
polybar bspwm-bar-top &

killall xscreensaver
xscreensaver &

pgrep -x sxhkd > /dev/null || sxhkd &


bspc monitor -d I II III IV V VI VII VIII IX X


bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true


#open Funny Java Things
bspc config focus_follows_pointer false
wmname LG3D

#Polybar padding madness, gotta check this later.
#bspc config ignore_ewmh_struts true

###### THEMES ##############################

bspc config normal_border_color  "#151515"
bspc config active_border_color  "#151515"
#bspc config focused_border_color "#F414AD"   #Pink
#bspc config focused_border_color "#FF4000"   #Orange   
#bspc config focused_border_color "#FE2E2E"   #Light-red
bspc config focused_border_color "#ffb52a"   #Yellow
#bspc config focused_border_color "#8000FF"   # Purple 

bspc config border_width         1
bspc config window_gap           7
#bspc config border_radius        8


#bspc config focus_follows_pointer true
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
bspc rule -a android-studio state=floating

####### INICIALIZATION PROGRAMS ##########

# COMANDOS INICIAIS ///////////////////////////////////////////////////////////////////
#
# Compositor##################################
#picom --config ~/.config/picom/picom.sample.conf 
##############################################
#
#
#
## Wallpaper ##################################
#nitrogen --restore                                        # Nitrogen set wallpaper
#paperview ~/Imagens/wallpapers/pixl/gifs/trainstation/ 5  #Paperview animated set wallpaper
#wal -R                                                     # Pywall colorscheme and wallpaper
###############################################
#
#
#
## Basic Apps #################################
#
#dunst -conf $HOME/.config/dunst/dunstrc-bspwm
#xscreensaver-systemd
#xscreensaver 
#polybar bspwm-bar-top
#killall nm-applet


#/////////////////////////////////////////////////////////////////////////////////////




